/**
 * offers.service.js
 *
 * Owns offer creation orchestration and the offer token itself. `createInitialOffer()` (P5-3) is
 * the cancellation flow's OFFER_RESERVED branch: called from inside
 * bookings.service.js#cancelBooking's own transaction, once per category that has a waiting
 * entry. `generateOfferToken()` (P5-4) is the literal docs/PROJECT_PROMPT.md §7.3 shape.
 *
 * Does NOT own: the SQL itself (offers.queries.js), picking who gets offered a seat
 * (waitlist.queries.js#claimNextWaitingEntry, already run by the caller before this is invoked),
 * verifying a PRESENTED token against a stored hash at accept time (P5-5, not built yet -- this
 * file only knows how to MINT a token, not validate one back), or the cascade re-offer that mints
 * a fresh token for the same seats after this offer lapses (dropped -- see docs/BUILD_LOG.md's
 * Phase 5 scope decision, 2026-08-24; §7.4's cascade is designed but not wired).
 */

import crypto from 'node:crypto';

import { SEAT_STATES } from 'shared/seatStates.js';
import { assertTransition } from '../seatmap/seatState.machine.js';
import * as offersQueries from './offers.queries.js';
import * as waitlistQueries from './waitlist.queries.js';

/**
 * The literal docs/PROJECT_PROMPT.md §7.3 shape: a raw token embedding the offer's own id (so a
 * caller presenting one back can be traced to a specific offer at a glance, e.g. in logs, even
 * before the hash is checked), hashed with SHA-256 for storage. Only `tokenHash` is ever written
 * to the database (`waitlist_offers.token_hash`) -- `raw` exists only in memory and, once P4-7
 * builds the waitlist-offer email, in the claim link it sends. Nothing else in this codebase may
 * persist `raw`; that's the whole point of "single-use" being enforceable at all -- if the raw
 * value were recoverable from storage, presenting the stored value would work as well as knowing
 * the value actually emailed to the offeree.
 *
 * WHY the id has to be generated here, client-side, rather than left to the column's own
 * `gen_random_uuid()` default: the raw token's own format embeds it
 * (`${offerId}.${randomBytes}`), so the id must be known BEFORE the INSERT that would otherwise
 * generate it. `offers.queries.js#insertWaitlistOffer` takes this id explicitly instead.
 *
 * WHY SHA-256 over a random value, not a real HMAC (the §7.3 heading's own name for this
 * mechanism, despite the code sample it shows being a plain hash): the 32 bytes of
 * `crypto.randomBytes` are the secret here, not a shared key -- an attacker who doesn't already
 * know the raw token cannot forge one that hashes to a value in `waitlist_offers`, because they
 * cannot guess 256 random bits. A proper HMAC exists to authenticate a message under a KNOWN key
 * two parties share; nothing here needs that property, since there's no message being
 * authenticated -- the token IS the secret. Matches §7.3's own literal code sample, not its
 * heading's name for it.
 *
 * @param {string} offerId - the offer row's own id, generated by the caller (createInitialOffer())
 *   BEFORE the row exists, specifically so it can be embedded here
 * @returns {{ raw: string, tokenHash: string }} `raw` is for the caller to build a claim link
 *   with; `tokenHash` is what gets stored
 */
export function generateOfferToken(offerId) {
  const raw = `${offerId}.${crypto.randomBytes(32).toString('base64url')}`;
  const tokenHash = crypto.createHash('sha256').update(raw).digest('hex');
  return { raw, tokenHash };
}

/**
 * Converts one category's freed seats into a live offer for the waiting entry the caller already
 * claimed (waitlist.queries.js#claimNextWaitingEntry, under FOR UPDATE, in the SAME transaction).
 * Must be called from inside that transaction -- see bookings.service.js#cancelBooking's own
 * WALKTHROUGH for why the whole dispatch (booking cancel, seat transition, this offer, the entry's
 * status flip) has to commit or roll back as one unit: a committed cancellation with a rolled-back
 * offer would leave seats OFFER_RESERVED for nobody -- invisible to the seat map, never swept by
 * any TTL layer built so far (all three key off show_seats.expires_at/reserved_until existing
 * alongside a real offer, not off a bare seat state), and not recoverable by any mechanism this
 * codebase has.
 *
 * @param {import('pg').PoolClient} client - must already be inside a transaction
 * @param {{ bookingId: string, categoryId: string, waitlistEntryId: string, offerTtlSeconds: number, maxCascadeAttempts: number }} params
 * @returns {Promise<{ seats: Array<{ showSeatId: string, seatId: string }>, offer: object, rawToken: string }>}
 *   `rawToken` is for whichever caller sends the offer email (P4-7) to build the claim link with
 *   -- it is NEVER persisted anywhere; only `offer.tokenHash` (already written to
 *   `waitlist_offers.token_hash`) survives this function returning
 * @throws never; this function trusts the caller has already confirmed a waiting entry exists and
 *   that this category genuinely has BOOKED seats to transition -- an empty result here would be a
 *   caller bug, not a normal outcome, so it's not specially handled
 */
export async function createInitialOffer(
  client,
  { bookingId, categoryId, waitlistEntryId, offerTtlSeconds, maxCascadeAttempts }
) {
  // The D-40 call site docs/BUILD_LOG.md's Decisions Ledger anticipated for this exact pair
  // (BOOKED -> OFFER_RESERVED) -- this is the FIRST offer (attempt_no: 1). A cascade re-offer
  // would have been OFFER_RESERVED -> OFFER_RESERVED (the self-loop shared/seatStates.js
  // documents separately), but that cascade is dropped, not built -- see this file's own header.
  assertTransition(SEAT_STATES.BOOKED, SEAT_STATES.OFFER_RESERVED);

  // docs/PROJECT_PROMPT.md §7.2, D-14: reserved_until is the fixed outer bound the WHOLE cascade
  // must finish inside -- a hard upper bound on how long ANY legitimate cascade can run, computed
  // once here and never touched again. (No cascade exists to re-extend it in any case -- see this
  // file's own header -- but the value is still meaningful: it's what makes this offer's seats
  // stay exclusive, per D-7, for the ENTIRE window a legitimate cascade could have run in, not
  // just this one attempt's own offerTtlSeconds.)
  const reservedUntilSeconds = offerTtlSeconds * maxCascadeAttempts + 60;

  const seats = await offersQueries.transitionBookedSeatsToOfferReserved(client, {
    bookingId,
    categoryId,
    offerTtlSeconds,
    reservedUntilSeconds,
  });

  // Generated here, before the INSERT, so the id can be embedded in the raw token itself -- see
  // generateOfferToken()'s own header.
  const offerId = crypto.randomUUID();
  const { raw: rawToken, tokenHash } = generateOfferToken(offerId);

  const offer = await offersQueries.insertWaitlistOffer(client, {
    id: offerId,
    waitlistEntryId,
    showSeatIds: seats.map((seat) => seat.showSeatId),
    tokenHash,
    attemptNo: 1,
    offerTtlSeconds,
  });

  await waitlistQueries.markEntryOffered(client, waitlistEntryId);

  return { seats, offer, rawToken };
}
