/**
 * offers.service.js
 *
 * Owns offer creation orchestration and the offer token itself. `createInitialOffer()` (P5-3) is
 * the cancellation flow's OFFER_RESERVED branch: called from inside
 * bookings.service.js#cancelBooking's own transaction, once per category that has a waiting
 * entry. `generateOfferToken()` (P5-4) is the literal docs/PROJECT_PROMPT.md §7.3 shape.
 *
 * Does NOT own: the SQL itself (offers.queries.js), picking who gets offered a seat
 * (waitlist.queries.js#claimNextWaitingEntry, already run by the caller before this is invoked),
 * or the cascade re-offer that mints a fresh token for the same seats after this offer lapses
 * (dropped -- see docs/BUILD_LOG.md's Phase 5 scope decision, 2026-08-24; §7.4's cascade is
 * designed but not wired). `getOfferByToken()`/`acceptOffer()` (P5-5) verify a PRESENTED token
 * against the stored hash and, on accept, mint the booking the same way
 * bookings.service.js#confirmBooking does for a hold.
 */

import crypto from 'node:crypto';

import { pool } from '../../db/pool.js';
import { withTransaction } from '../../db/withTransaction.js';
import { env } from '../../config/env.js';
import { SEAT_STATES } from 'shared/seatStates.js';
import { assertTransition } from '../seatmap/seatState.machine.js';
import { OfferInvalidError, OfferExpiredError } from '../../utils/errors.js';
import * as offersQueries from './offers.queries.js';
import * as waitlistQueries from './waitlist.queries.js';
import * as bookingsQueries from '../bookings/bookings.queries.js';
import * as paymentsService from '../payments/payments.service.js';
import {
  generatePlaceholderReference,
  generatePlaceholderQrToken,
} from '../bookings/bookings.service.js';

/**
 * The literal docs/PROJECT_PROMPT.md §7.3 shape: a raw token embedding the offer's own id (so a
 * caller presenting one back can be traced to a specific offer at a glance, e.g. in logs, even
 * before the hash is checked), hashed with SHA-256 for storage. Only `tokenHash` is ever written
 * to the database (`waitlist_offers.token_hash`) -- `raw` exists only in memory and, once P4-7
 * builds the waitlist-offer email, in the claim link it sends. Nothing else in this codebase may
 * persist `raw`; that's the whole point of "single-use" being enforceable at all -- if the raw
 * value were recoverable from storage, presenting the stored value would work as well as knowing
 * the value actually emailed to the offeree.
 *
 * WHY the id has to be generated here, client-side, rather than left to the column's own
 * `gen_random_uuid()` default: the raw token's own format embeds it
 * (`${offerId}.${randomBytes}`), so the id must be known BEFORE the INSERT that would otherwise
 * generate it. `offers.queries.js#insertWaitlistOffer` takes this id explicitly instead.
 *
 * WHY SHA-256 over a random value, not a real HMAC (the §7.3 heading's own name for this
 * mechanism, despite the code sample it shows being a plain hash): the 32 bytes of
 * `crypto.randomBytes` are the secret here, not a shared key -- an attacker who doesn't already
 * know the raw token cannot forge one that hashes to a value in `waitlist_offers`, because they
 * cannot guess 256 random bits. A proper HMAC exists to authenticate a message under a KNOWN key
 * two parties share; nothing here needs that property, since there's no message being
 * authenticated -- the token IS the secret. Matches §7.3's own literal code sample, not its
 * heading's name for it.
 *
 * @param {string} offerId - the offer row's own id, generated by the caller (createInitialOffer())
 *   BEFORE the row exists, specifically so it can be embedded here
 * @returns {{ raw: string, tokenHash: string }} `raw` is for the caller to build a claim link
 *   with; `tokenHash` is what gets stored
 */
export function generateOfferToken(offerId) {
  const raw = `${offerId}.${crypto.randomBytes(32).toString('base64url')}`;
  const tokenHash = crypto.createHash('sha256').update(raw).digest('hex');
  return { raw, tokenHash };
}

/**
 * Converts one category's freed seats into a live offer for the waiting entry the caller already
 * claimed (waitlist.queries.js#claimNextWaitingEntry, under FOR UPDATE, in the SAME transaction).
 * Must be called from inside that transaction -- see bookings.service.js#cancelBooking's own
 * WALKTHROUGH for why the whole dispatch (booking cancel, seat transition, this offer, the entry's
 * status flip) has to commit or roll back as one unit: a committed cancellation with a rolled-back
 * offer would leave seats OFFER_RESERVED for nobody -- invisible to the seat map, never swept by
 * any TTL layer built so far (all three key off show_seats.expires_at/reserved_until existing
 * alongside a real offer, not off a bare seat state), and not recoverable by any mechanism this
 * codebase has.
 *
 * @param {import('pg').PoolClient} client - must already be inside a transaction
 * @param {{ bookingId: string, categoryId: string, waitlistEntryId: string, offerTtlSeconds: number, maxCascadeAttempts: number }} params
 * @returns {Promise<{ seats: Array<{ showSeatId: string, seatId: string }>, offer: object, rawToken: string }>}
 *   `rawToken` is for whichever caller sends the offer email (P4-7) to build the claim link with
 *   -- it is NEVER persisted anywhere; only `offer.tokenHash` (already written to
 *   `waitlist_offers.token_hash`) survives this function returning
 * @throws never; this function trusts the caller has already confirmed a waiting entry exists and
 *   that this category genuinely has BOOKED seats to transition -- an empty result here would be a
 *   caller bug, not a normal outcome, so it's not specially handled
 */
export async function createInitialOffer(
  client,
  { bookingId, categoryId, waitlistEntryId, offerTtlSeconds, maxCascadeAttempts }
) {
  // The D-40 call site docs/BUILD_LOG.md's Decisions Ledger anticipated for this exact pair
  // (BOOKED -> OFFER_RESERVED) -- this is the FIRST offer (attempt_no: 1). A cascade re-offer
  // would have been OFFER_RESERVED -> OFFER_RESERVED (the self-loop shared/seatStates.js
  // documents separately), but that cascade is dropped, not built -- see this file's own header.
  assertTransition(SEAT_STATES.BOOKED, SEAT_STATES.OFFER_RESERVED);

  // docs/PROJECT_PROMPT.md §7.2, D-14: reserved_until is the fixed outer bound the WHOLE cascade
  // must finish inside -- a hard upper bound on how long ANY legitimate cascade can run, computed
  // once here and never touched again. (No cascade exists to re-extend it in any case -- see this
  // file's own header -- but the value is still meaningful: it's what makes this offer's seats
  // stay exclusive, per D-7, for the ENTIRE window a legitimate cascade could have run in, not
  // just this one attempt's own offerTtlSeconds.)
  const reservedUntilSeconds = offerTtlSeconds * maxCascadeAttempts + 60;

  const seats = await offersQueries.transitionBookedSeatsToOfferReserved(client, {
    bookingId,
    categoryId,
    offerTtlSeconds,
    reservedUntilSeconds,
  });

  // Generated here, before the INSERT, so the id can be embedded in the raw token itself -- see
  // generateOfferToken()'s own header.
  const offerId = crypto.randomUUID();
  const { raw: rawToken, tokenHash } = generateOfferToken(offerId);

  const offer = await offersQueries.insertWaitlistOffer(client, {
    id: offerId,
    waitlistEntryId,
    showSeatIds: seats.map((seat) => seat.showSeatId),
    tokenHash,
    attemptNo: 1,
    offerTtlSeconds,
  });

  await waitlistQueries.markEntryOffered(client, waitlistEntryId);

  return { seats, offer, rawToken };
}

/**
 * @param {string} rawToken
 * @returns {Promise<{ seats: object[], subtotalCents: number, totalCents: number, secondsRemaining: number, showId: string, categoryId: string }>}
 * @throws {OfferInvalidError} no offer matches this token's hash, or it isn't PENDING
 * @throws {OfferExpiredError} the offer is PENDING but its expires_at has passed
 */
export async function getOfferByToken(rawToken) {
  const tokenHash = crypto.createHash('sha256').update(rawToken).digest('hex');
  const offer = await offersQueries.findOfferByTokenHash(pool, tokenHash);
  if (!offer || offer.status !== 'PENDING') throw new OfferInvalidError();
  if (offer.isExpired) throw new OfferExpiredError();

  const seats = await offersQueries.findOfferSeatsByIds(pool, offer.showSeatIds);
  const subtotalCents = seats.reduce((sum, seat) => sum + (seat.priceCents ?? 0), 0);
  const feesCents = Math.round((subtotalCents * env.BOOKING_FEE_PERCENT) / 100);

  return {
    seats,
    subtotalCents,
    totalCents: subtotalCents + feesCents,
    secondsRemaining: offer.secondsRemaining,
    showId: seats[0]?.showId,
    categoryId: seats[0]?.categoryId,
  };
}

/**
 * WALKTHROUGH: acceptOffer(), reusing confirmBooking()'s guarded-transaction shape (D-40) with a
 * genuinely different `fromState` at last
 *
 * 1. Look up the offer by token hash (not FOR UPDATE -- advisory, same reasoning as
 *    bookings.queries.js#findHoldSeats: the correctness boundary is step 5's atomic UPDATE, not
 *    this read). Not found, or not PENDING, or expired -> OfferInvalidError/OfferExpiredError
 *    before any write -- mirrors confirmBooking()'s immediate HoldExpiredError for an empty
 *    findHoldSeats() result.
 * 2. Look up the offeree's own userId via the offer's waitlistEntryId -- this endpoint is public,
 *    token-authenticated (§7.3), not `requireAuth`-gated, so there is no req.user to fall back on;
 *    the token itself is the authorization, exactly like the entry it names.
 * 3. Insert the booking (status CONFIRMED directly, same reasoning as confirmBooking() -- this
 *    mock gateway never declines) and capture payment, reusing confirmBooking()'s own placeholder
 *    reference/QR generators rather than a second copy.
 * 4. assertTransition(OFFER_RESERVED, BOOKED) -- the D-40 call site this codebase has been
 *    carrying a comment about since P4-2: this is the FIRST place `fromState` is something other
 *    than the literal HELD confirmBooking() always passes.
 * 5. offers.queries.js#confirmOfferSeats() -- the atomic guarded UPDATE, gated on
 *    `state = 'OFFER_RESERVED' AND expires_at > now()` for this offer's EXACT seat ids. This is
 *    the real single-use boundary: a double-accept race (the same token POSTed twice) has both
 *    transactions target the identical seat set, so the loser's predicate matches nothing once the
 *    winner commits -- see that function's own WALKTHROUGH.
 * 6. A short RETURNING (including empty) rolls back the whole transaction --
 *    booking/payment/nothing survives -- and reports OfferInvalidError, same shortfall idiom as
 *    confirmBooking()'s own step 6.
 * 7. bookings.queries.js#insertBookingSeats() -- the historical price record, same as every other
 *    booking path.
 * 8. offers.queries.js#markOfferAccepted() / waitlist.queries.js#markEntryConverted() --
 *    bookkeeping, predicate-gated for idempotency, not the correctness boundary (step 5 already
 *    is).
 *
 * @param {string} rawToken
 * @returns {Promise<{ booking: object, seats: object[] }>}
 * @throws {OfferInvalidError} no offer matches this token's hash, it isn't PENDING, or a
 *   concurrent accept already won the seat-level race
 * @throws {OfferExpiredError} the offer is PENDING but its expires_at has passed
 */
export async function acceptOffer(rawToken) {
  const tokenHash = crypto.createHash('sha256').update(rawToken).digest('hex');

  return withTransaction(async (client) => {
    const offer = await offersQueries.findOfferByTokenHash(client, tokenHash);
    if (!offer || offer.status !== 'PENDING') throw new OfferInvalidError();
    if (offer.isExpired) throw new OfferExpiredError();

    const entry = await waitlistQueries.findEntryById(client, offer.waitlistEntryId);
    const seats = await offersQueries.findOfferSeatsByIds(client, offer.showSeatIds);

    const subtotalCents = seats.reduce((sum, seat) => sum + (seat.priceCents ?? 0), 0);
    const feesCents = Math.round((subtotalCents * env.BOOKING_FEE_PERCENT) / 100);
    const totalCents = subtotalCents + feesCents;

    const booking = await bookingsQueries.insertBooking(client, {
      reference: generatePlaceholderReference(),
      showId: entry.showId,
      userId: entry.userId,
      subtotalCents,
      feesCents,
      totalCents,
      qrToken: generatePlaceholderQrToken(),
    });

    await paymentsService.authorizeAndCapture(client, { bookingId: booking.id, amountCents: totalCents });

    // The D-40 call site -- see this function's own WALKTHROUGH step 4.
    assertTransition(SEAT_STATES.OFFER_RESERVED, SEAT_STATES.BOOKED);

    const confirmedSeatIds = await offersQueries.confirmOfferSeats(client, {
      showSeatIds: offer.showSeatIds,
      bookingId: booking.id,
    });
    if (confirmedSeatIds.length < offer.showSeatIds.length) {
      throw new OfferInvalidError();
    }

    await bookingsQueries.insertBookingSeats(
      client,
      booking.id,
      seats.map((seat) => ({ showSeatId: seat.showSeatId, priceCents: seat.priceCents }))
    );
    await offersQueries.markOfferAccepted(client, offer.id);
    await waitlistQueries.markEntryConverted(client, entry.id);

    return { booking, seats };
  });
}
